use gifsicle --batch mode

diff --git a/.config/init/funcs/gifo b/.config/init/funcs/gifo
--- a/.config/init/funcs/gifo
+++ b/.config/init/funcs/gifo
@@ -13,9 +13,8 @@ for i in $@; do
 		done
 		du -h "$i" | cut -f 1 | read before
 		echo "$i..."
-		gifsicle --no-ignore-errors -w -O3 "$i" -o "$i.out"
-		[[ -f "$ofile" ]] && rm "$i" && mv "$ofile" "$i" && \
-		du -h "$i" | cut -f 1 | read after && \
-		echo "   $before -> $after" || echo "  failed"
+		gifsicle --batch --no-ignore-errors -w -O3 -i "$i" \
+		&& du -h "$i" | cut -f 1 | read after \
+		&& echo "   $before -> $after" || echo "  failed"
 	fi
 done
